FROM node:20-alpine

WORKDIR /nextjs2025

# Copy package.json & cài dependencies
COPY package*.json ./
RUN npm install

# Copy toàn bộ source
COPY . .

EXPOSE 3000

# CMD chạy Next.js dev server
CMD ["npm", "run", "dev"]
